# Generated by Django 4.2.4 on 2023-09-26 10:05

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service_app', '0006_service_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rodada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_fim', models.DateTimeField(default=datetime.datetime(2023, 9, 27, 10, 5, 17, 543649, tzinfo=datetime.timezone.utc))),
                ('status', models.CharField(choices=[('A', 'Aberta'), ('F', 'Fechada')], default='A', max_length=1)),
                ('numero', models.PositiveIntegerField(default=0)),
                ('ano_referencia', models.IntegerField(default=2023)),
                ('mes_referencia', models.PositiveSmallIntegerField(choices=[(1, 'Janeiro'), (2, 'Fevereiro'), (3, 'Março'), (4, 'Abril'), (5, 'Maio'), (6, 'Junho'), (7, 'Julho'), (8, 'Agosto'), (9, 'Setembro'), (10, 'Outubro'), (11, 'Novembro'), (12, 'Dezembro')], default=9)),
                ('services', models.ManyToManyField(blank=True, related_name='rodadas', to='service_app.service')),
            ],
        ),
    ]
