# Generated by Django 4.2.4 on 2023-09-26 11:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodadas', '0005_alter_rodada_data_fim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rodada',
            name='data_fim',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 27, 11, 17, 22, 392010, tzinfo=datetime.timezone.utc)),
        ),
    ]
