# Generated by Django 4.2.4 on 2023-09-26 18:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodadas', '0008_alter_rodada_data_fim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rodada',
            name='data_fim',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 27, 18, 46, 53, 795110, tzinfo=datetime.timezone.utc)),
        ),
    ]
