# Generated by Django 4.2.4 on 2023-08-05 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profile_app', '0001_initial'),
        ('service_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_opcao', models.PositiveSmallIntegerField()),
                ('data_solicitacao', models.DateField()),
                ('status', models.CharField(choices=[('S', 'Solicitado'), ('A', 'Agendado'), ('N', 'Negado')], max_length=1)),
                ('criterio', models.CharField(max_length=100)),
                ('id_mil', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='profile_app.military')),
                ('id_sv', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='service_app.service')),
            ],
        ),
    ]
