# Generated by Django 4.2.3 on 2023-08-06 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0003_rename_militar_service_militares'),
        ('profile_app', '0003_alter_permission_militar_alter_scheduling_militar'),
        ('request_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='id_mil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile_app.military'),
        ),
        migrations.AlterField(
            model_name='requests',
            name='id_sv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_app.service'),
        ),
    ]
