# Generated by Django 4.2.4 on 2023-08-25 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0006_service_status'),
        ('profile_app', '0003_alter_permission_militar_alter_scheduling_militar'),
        ('request_app', '0002_alter_requests_id_mil_alter_requests_id_sv'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Requests',
            new_name='Request',
        ),
    ]
