# Generated by Django 4.2.4 on 2023-09-18 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_app', '0005_alter_request_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='criterio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
