# Generated by Django 4.2.4 on 2023-09-18 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0008_scheduling_mes_referencia_alter_scheduling_militar'),
        ('service_app', '0006_service_status'),
        ('request_app', '0006_alter_request_criterio'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='request',
            unique_together={('id_mil', 'id_sv')},
        ),
    ]
