# Generated by Django 4.2.4 on 2023-08-05 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0001_initial'),
        ('service_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='militar',
            field=models.ManyToManyField(related_name='servicos', to='profile_app.military'),
        ),
    ]
