# Generated by Django 4.2.3 on 2023-08-05 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0002_alter_service_militar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='militar',
            new_name='militares',
        ),
    ]
