# Generated by Django 4.2.3 on 2023-08-10 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0003_alter_permission_militar_alter_scheduling_militar'),
        ('service_app', '0004_service_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='service_images/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='data_inicio',
            field=models.DateField(verbose_name='Do dia'),
        ),
        migrations.AlterField(
            model_name='service',
            name='data_termino',
            field=models.DateField(verbose_name='Ao dia'),
        ),
        migrations.AlterField(
            model_name='service',
            name='hora_inicio',
            field=models.TimeField(default='08:00', verbose_name='Das'),
        ),
        migrations.AlterField(
            model_name='service',
            name='hora_termino',
            field=models.TimeField(default='08:00', verbose_name='Às'),
        ),
        migrations.AlterField(
            model_name='service',
            name='militares',
            field=models.ManyToManyField(blank=True, related_name='servicos', to='profile_app.military'),
        ),
        migrations.AlterField(
            model_name='service',
            name='observacao',
            field=models.TextField(verbose_name='Observação'),
        ),
    ]
