# Generated by Django 4.2.4 on 2023-08-25 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0005_service_image_alter_service_data_inicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='status',
            field=models.CharField(choices=[('A', 'Aberto'), ('F', 'Fechado')], default='A', max_length=1),
        ),
    ]
