# Generated by Django 4.2.4 on 2023-09-07 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0003_alter_permission_militar_alter_scheduling_militar'),
    ]

    operations = [
        migrations.CreateModel(
            name='BancoDeHoras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BancoDePontos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontos', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='military',
            name='banco_de_horas',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='profile_app.bancodehoras', verbose_name='Banco de horas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='military',
            name='banco_de_pontos',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='profile_app.bancodepontos', verbose_name='Banco de pontos'),
            preserve_default=False,
        ),
    ]
