# Generated by Django 4.2.4 on 2023-09-07 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0004_bancodehoras_bancodepontos_military_banco_de_horas_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bancodehoras',
            options={'verbose_name': 'Banco de Horas', 'verbose_name_plural': 'Bancos de Horas'},
        ),
        migrations.AlterModelOptions(
            name='bancodepontos',
            options={'verbose_name': 'Banco de Pontos', 'verbose_name_plural': 'Bancos de Pontos'},
        ),
        migrations.AlterModelOptions(
            name='military',
            options={'verbose_name': 'Militar', 'verbose_name_plural': 'Militares'},
        ),
        migrations.AlterModelOptions(
            name='permission',
            options={'verbose_name': 'Permissão', 'verbose_name_plural': 'Permissões'},
        ),
        migrations.AlterModelOptions(
            name='scheduling',
            options={'verbose_name': 'Agendamento', 'verbose_name_plural': 'Agendamentos'},
        ),
        migrations.AlterField(
            model_name='military',
            name='banco_de_horas',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='profile_app.bancodehoras', verbose_name='Banco de horas'),
        ),
        migrations.AlterField(
            model_name='military',
            name='banco_de_pontos',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='profile_app.bancodepontos', verbose_name='Banco de pontos'),
        ),
    ]
