# Generated by Django 4.2.4 on 2023-09-08 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0005_alter_bancodehoras_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='military',
            name='banco_de_horas',
        ),
        migrations.RemoveField(
            model_name='military',
            name='banco_de_pontos',
        ),
        migrations.AddField(
            model_name='bancodehoras',
            name='militar',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='profile_app.military'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bancodepontos',
            name='militar',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='profile_app.military'),
            preserve_default=False,
        ),
    ]
