# Generated by Django 4.2.4 on 2023-09-15 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0006_remove_military_banco_de_horas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduling',
            name='militar',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profile_app.military'),
        ),
    ]
