# Generated by Django 4.2.4 on 2023-09-15 09:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0007_alter_scheduling_militar'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduling',
            name='mes_referencia',
            field=models.DateField(default=datetime.datetime(2023, 9, 15, 9, 44, 22, 363149, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scheduling',
            name='militar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile_app.military'),
        ),
    ]
