# Generated by Django 4.2.4 on 2023-09-07 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profile_app', '0004_bancodehoras_bancodepontos_military_banco_de_horas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Recompensa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equivalente_horas', models.SmallIntegerField(verbose_name='equivalente em horas')),
                ('equivalente_pontos', models.SmallIntegerField(verbose_name='equivalente em pontos')),
                ('delito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocorrencia.delito')),
            ],
        ),
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('local', models.CharField(max_length=100)),
                ('documento', models.FileField(upload_to='sistema_de_pontos/%Y/%m/')),
                ('delitos', models.ManyToManyField(related_name='situacoes', to='ocorrencia.delito')),
                ('militares', models.ManyToManyField(related_name='ocorrencias', to='profile_app.military')),
            ],
        ),
    ]
