# Generated by Django 4.2.4 on 2023-09-07 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencia', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delito',
            options={'verbose_name': 'Delito', 'verbose_name_plural': 'Delitos'},
        ),
        migrations.AlterModelOptions(
            name='ocorrencia',
            options={'verbose_name': 'Ocorrência', 'verbose_name_plural': 'Ocorrências'},
        ),
        migrations.AlterModelOptions(
            name='recompensa',
            options={'verbose_name': 'Recompensa', 'verbose_name_plural': 'Recompensas'},
        ),
    ]
